"use client";

import Header from "@/components/Header";
import Menu from "@/components/Menu";
import Footer from "@/components/Footer";
import { Providers } from "./providers";

import "../styles/index.css";

/*export const metadata = {
  title: "Blog",
  description: "Blog generated by create next app",
};*/

export default function RootLayout({ children }) {
  return (
    <html suppressHydrationWarning  lang="en">
      <body className={`bg-[#FCFCFC] dark:bg-black`}>
        <Providers>
          <Header />
          <Menu />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
