const fields = [
  {
    id: "category",
    label: "Categorias",
    value: "",
    align: "right",
    showOnTable: false,
    type: "text",
    defaultValue: "",
    showOnForm: true,
    searchable: true,
    format: "",
    selectLabel: "",
    data: [],
  },
  {
    id: "author",
    label: "Autor",
    value: "",
    align: "right",
    showOnTable: true,
    type: "text",
    defaultValue: "",
    showOnForm: true,
    searchable: true,
    format: "",
    selectLabel: "",
    data: [],
  },
  {
    id: "title",
    label: "Titulo",
    value: "",
    align: "right",
    showOnTable: true,
    type: "text",
    defaultValue: "",
    showOnForm: true,
    searchable: true,
    format: "",
    selectLabel: "",
    data: [],
  },
  {
    id: "publishedAt",
    label: "Fecha de publicación",
    value: "",
    align: "left",
    showOnTable: true,
    type: "fullDate",
    defaultValue: "",
    showOnForm: true,
    searchable: true,
    format: "",
    selectLabel: "",
    data: [],
  }
];

export const entityConfiguration = {
  entity: "",
  title: "Posts",
  url: "",
  fields: fields
}